version: '3.8'

services:
  web:
    image: 184701572359.dkr.ecr.ap-south-1.amazonaws.com/catalyst:web
    command: gunicorn netly.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/netly/web/staticfiles
      - media_volume:/home/netly/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx-proxy:
    container_name: nginx-proxy
    image: 184701572359.dkr.ecr.ap-south-1.amazonaws.com/catalyst:nginx-proxy
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/home/netly/web/staticfiles
      - media_volume:/home/netly/web/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web
  acme-companion:
    image: nginxproxy/acme-companion
    env_file:
      - ./.env.prod.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme: